# Generated by Django 5.1.2 on 2024-11-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_newscategory_news_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
