# Generated by Django 5.1.2 on 2024-11-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_delete_holiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'Yangilik katigoriyasi', 'verbose_name_plural': 'Yangilik kategoriyalari'},
        ),
    ]
