# Generated by Django 5.1.2 on 2024-11-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_newscategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='location',
        ),
        migrations.AddField(
            model_name='news',
            name='location_i_frame',
            field=models.TextField(blank=True, null=True),
        ),
    ]
