# Generated by Django 5.1.2 on 2024-11-26 10:21

import client.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_festivalcategory_festival'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festival',
            options={'verbose_name': 'Festival', 'verbose_name_plural': 'Festivallar'},
        ),
        migrations.CreateModel(
            name='FestivalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=client.models.festival_image_upload_path)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='client.festival')),
            ],
            options={
                'verbose_name': 'Festival rasm',
                'verbose_name_plural': 'Festival rasmlari',
            },
        ),
    ]
