# Generated by Django 5.1.2 on 2024-11-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_festival_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
