# Generated by Django 5.1.2 on 2024-11-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_newscategory_name_ru_newscategory_name_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategory',
            name='name',
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
