# Generated by Django 5.1.2 on 2024-11-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_remove_newscategory_name_newscategory_name_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='address',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='description',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='name',
        ),
        migrations.AddField(
            model_name='festival',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='address_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
