# Generated by Django 5.1.2 on 2024-11-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_news_content_en_news_content_ru_news_title_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='content_uz',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title_uz',
        ),
    ]
