# Generated by Django 5.1.2 on 2024-11-28 06:52

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_socialmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Ijtimoiy tarmoq', 'verbose_name_plural': 'Ijtimoiy tarmoqlar'},
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='name',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.social_media_icon_upload_path),
        ),
    ]
