# Generated by Django 5.1.2 on 2024-11-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_alter_socialmedia_options_remove_socialmedia_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='icon',
        ),
    ]
