# Generated by Django 5.1.2 on 2024-11-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_sponsor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='name_en',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='name_uz',
        ),
    ]
