# Generated by Django 5.1.2 on 2024-11-28 10:35

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.about_us_image_upload_path),
        ),
    ]
