# Generated by Django 5.1.2 on 2024-11-28 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_alter_photogallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Fotogalereya kategoriyasi',
                'verbose_name_plural': 'Fotogalereya kategoriyalari',
            },
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_galleries', to='client.photogallerycategory'),
        ),
    ]
