# Generated by Django 5.1.2 on 2024-11-28 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_photogallerycategory_alter_photogallery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_galleries', to='client.photogallerycategory'),
        ),
    ]
