# Generated by Django 5.1.2 on 2024-11-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_alter_festivalposter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festivalposter',
            options={'verbose_name': 'Festival Poster', 'verbose_name_plural': 'Festival Poster'},
        ),
    ]
