# Generated by Django 5.1.2 on 2024-11-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_alter_festivalposter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('additional_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=255)),
                ('location_i_frame', models.TextField(blank=True, null=True)),
                ('postal_index', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': "Bog'lanish",
                'verbose_name_plural': "Bog'lanish",
            },
        ),
    ]
