# Generated by Django 5.1.2 on 2024-11-29 05:36

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_remove_contact_address_contact_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.photo_gallery_image_upload_path),
        ),
    ]
