# Generated by Django 5.1.2 on 2025-02-09 18:54

import client.models
import client.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0032_photogallery_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.about_us_image_upload_path, validators=[client.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='festival',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.festival_image_upload_path, validators=[client.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='festivalimage',
            name='image',
            field=models.ImageField(upload_to=client.models.festival_image_upload_path, validators=[client.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='festivalposter',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.festival_poster_logo_upload_path, validators=[client.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='festivalposter',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=client.models.festival_poster_video_upload_path, validators=[client.validators.validate_video_size, client.validators.validate_video_file]),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=client.models.news_image_upload_path, validators=[client.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to=client.models.news_image_upload_path, validators=[client.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.photo_gallery_image_upload_path, validators=[client.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='photogalleryimage',
            name='image',
            field=models.ImageField(upload_to=client.models.photo_gallery_image_upload_path, validators=[client.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.sponsor_logo_upload_path, validators=[client.validators.validate_image_size]),
        ),
    ]
